name: Memo Append

on:
  repository_dispatch:
    types: [add-memo]

jobs:
  update-memo:
    runs-on: ubuntu-latest
    steps:
      # 1. コードをチェックアウト (GITHUB_TOKEN を無視)
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. メモを追記
      - name: Append memo
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') ${{ github.event.client_payload.note }}" >> memo.md

      # 3. Commit & Push using PAT
      - name: Commit & Push using PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH=add-memo
          git checkout -B $BRANCH

          git status
          git add memo.md
          git commit -m "Add memo" || echo "No changes to commit"

          git push https://x-access-token:${PAT_TOKEN}@github.com/si-tm/train-routine.git $BRANCH

      # 4. Pull Request 作成または更新
      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: add-memo      # PR で使用するブランチ
          base: main            # PR のベース
          title: "Add memo from Worker"
          body: "This PR adds new memos submitted via Worker."
